// AS 테스트 데이터 시딩 스크립트
const { PrismaClient } = require('@prisma/client');

const prisma = new PrismaClient();

async function seedAfterService() {
  console.log('AS 테스트 데이터 시딩 시작...');

  // 기존 AS 데이터 삭제
  await prisma.afterService.deleteMany({});
  console.log('기존 AS 데이터 삭제 완료');

  // 고객 가져오기 (없으면 생성)
  let customer = await prisma.customer.findFirst();
  if (!customer) {
    customer = await prisma.customer.create({
      data: {
        name: '홍길동',
        email: 'hong@example.com',
        phone: '010-1234-5678',
        company: '테스트 회사',
        status: 'ACTIVE',
        segment: 'VIP',
      },
    });
    console.log('테스트 고객 생성:', customer.name);
  }

  // AS 테스트 데이터
  const asData = [
    {
      ticketNumber: 'AS-20251201-001',
      serviceDate: new Date('2025-12-01'),
      companyName: '클린에어 코리아',
      customerId: customer.id,
      customerName: '김철수',
      customerPhone: '010-1111-2222',
      customerAddress: '서울시 강남구 테헤란로 123',
      productName: '쉴드에어 프로',
      modelNumber: 'SH-AP100',
      issueType: 'NOISE',
      issueTitle: '작동 중 이상 소음 발생',
      issueDescription: '공기청정기 작동 시 웅웅거리는 소음이 발생합니다.',
      repairContent: '팬 모터 교체',
      status: 'COMPLETED',
      priority: 'HIGH',
      completedDate: new Date('2025-12-05'),
      diagnosisResult: '팬 모터 베어링 마모',
      repairDetails: '팬 모터 교체 및 테스트 완료',
      laborCost: 30000,
      partsCost: 50000,
      totalCost: 80000,
      filterReplaced: false,
      customerRating: 5,
      customerFeedback: '신속한 처리 감사합니다',
      createdAt: new Date('2025-12-01'),
    },
    {
      ticketNumber: 'AS-20251205-002',
      serviceDate: new Date('2025-12-05'),
      companyName: '에어솔루션',
      customerId: customer.id,
      customerName: '박영희',
      customerPhone: '010-3333-4444',
      customerAddress: '서울시 서초구 반포대로 456',
      productName: '쉴드에어 미니',
      modelNumber: 'SH-AP50',
      issueType: 'FILTER',
      issueTitle: '필터 교체 요청',
      issueDescription: '필터 교체 주기가 되어 교체 요청드립니다.',
      repairContent: 'HEPA 필터 및 활성탄 필터 교체',
      status: 'COMPLETED',
      priority: 'NORMAL',
      completedDate: new Date('2025-12-07'),
      diagnosisResult: '정상 교체 주기',
      repairDetails: 'HEPA 필터, 활성탄 필터 교체 완료',
      laborCost: 15000,
      partsCost: 45000,
      totalCost: 60000,
      filterReplaced: true,
      filterType: 'HEPA, 활성탄',
      nextFilterDate: new Date('2026-06-07'),
      customerRating: 4,
      customerFeedback: '만족합니다',
      createdAt: new Date('2025-12-05'),
    },
    {
      ticketNumber: 'AS-20251210-003',
      serviceDate: new Date('2025-12-10'),
      companyName: '클린에어 코리아',
      customerId: customer.id,
      customerName: '이민수',
      customerPhone: '010-5555-6666',
      customerAddress: '경기도 성남시 분당구 정자동 789',
      productName: '쉴드에어 프로 맥스',
      modelNumber: 'SH-AP200',
      issueType: 'SENSOR',
      issueTitle: '공기질 센서 오류',
      issueDescription: 'PM2.5 수치가 비정상적으로 높게 표시됩니다.',
      repairContent: '센서 모듈 교체',
      status: 'IN_PROGRESS',
      priority: 'HIGH',
      diagnosisResult: '먼지 센서 불량',
      laborCost: 20000,
      partsCost: 35000,
      totalCost: 55000,
      filterReplaced: false,
      createdAt: new Date('2025-12-10'),
    },
    {
      ticketNumber: 'AS-20251215-004',
      serviceDate: new Date('2025-12-15'),
      companyName: '에어솔루션',
      customerId: customer.id,
      customerName: '최지영',
      customerPhone: '010-7777-8888',
      customerAddress: '인천시 연수구 송도동 101',
      productName: '쉴드에어 미니',
      modelNumber: 'SH-AP50',
      issueType: 'POWER',
      issueTitle: '전원이 켜지지 않음',
      issueDescription: '콘센트에 연결해도 전원이 켜지지 않습니다.',
      status: 'RECEIVED',
      priority: 'URGENT',
      filterReplaced: false,
      createdAt: new Date('2025-12-15'),
    },
    {
      ticketNumber: 'AS-20251218-005',
      serviceDate: new Date('2025-12-18'),
      companyName: '클린에어 코리아',
      customerId: customer.id,
      customerName: '정수현',
      customerPhone: '010-9999-0000',
      customerAddress: '서울시 송파구 잠실동 202',
      productName: '쉴드에어 프로',
      modelNumber: 'SH-AP100',
      issueType: 'PERFORMANCE',
      issueTitle: '흡입력 저하',
      issueDescription: '필터 교체 후에도 흡입력이 약합니다.',
      repairContent: '팬 청소 및 점검',
      status: 'COMPLETED',
      priority: 'NORMAL',
      completedDate: new Date('2025-12-20'),
      diagnosisResult: '팬 먼지 누적으로 인한 성능 저하',
      repairDetails: '팬 분해 청소 및 성능 테스트 완료',
      laborCost: 25000,
      partsCost: 0,
      totalCost: 25000,
      filterReplaced: false,
      customerRating: 5,
      customerFeedback: '깨끗해졌어요!',
      createdAt: new Date('2025-12-18'),
    },
    {
      ticketNumber: 'AS-20251220-006',
      serviceDate: new Date('2025-12-20'),
      companyName: '에어솔루션',
      customerId: customer.id,
      customerName: '강민호',
      customerPhone: '010-1212-3434',
      customerAddress: '서울시 마포구 상암동 303',
      productName: '쉴드에어 프로 맥스',
      modelNumber: 'SH-AP200',
      issueType: 'ODOR',
      issueTitle: '악취 발생',
      issueDescription: '공기청정기에서 퀴퀴한 냄새가 납니다.',
      repairContent: '필터 교체 및 내부 청소',
      status: 'COMPLETED',
      priority: 'HIGH',
      completedDate: new Date('2025-12-22'),
      diagnosisResult: '활성탄 필터 수명 만료 및 내부 곰팡이',
      repairDetails: '전체 필터 교체, 내부 UV 살균 처리',
      laborCost: 30000,
      partsCost: 55000,
      totalCost: 85000,
      filterReplaced: true,
      filterType: 'HEPA, 활성탄, 탈취',
      nextFilterDate: new Date('2026-06-22'),
      customerRating: 4,
      customerFeedback: '냄새가 사라졌습니다',
      createdAt: new Date('2025-12-20'),
    },
    {
      ticketNumber: 'AS-20251222-007',
      serviceDate: new Date('2025-12-22'),
      companyName: '클린에어 코리아',
      customerId: customer.id,
      customerName: '윤서연',
      customerPhone: '010-5656-7878',
      customerAddress: '경기도 용인시 수지구 404',
      productName: '쉴드에어 미니',
      modelNumber: 'SH-AP50',
      issueType: 'NOISE',
      issueTitle: '바람 소리가 큼',
      issueDescription: '최대 풍속에서 바람 소리가 너무 큽니다.',
      status: 'DIAGNOSED',
      priority: 'LOW',
      diagnosisResult: '정상 작동 범위 내 소음',
      filterReplaced: false,
      createdAt: new Date('2025-12-22'),
    },
    {
      ticketNumber: 'AS-20251225-008',
      serviceDate: new Date('2025-12-25'),
      companyName: '에어솔루션',
      customerId: customer.id,
      customerName: '한지민',
      customerPhone: '010-2323-4545',
      customerAddress: '서울시 강동구 천호동 505',
      productName: '쉴드에어 프로',
      modelNumber: 'SH-AP100',
      issueType: 'FILTER',
      issueTitle: '필터 교체 알림',
      issueDescription: '필터 교체 알림이 떠서 접수합니다.',
      status: 'RECEIVED',
      priority: 'NORMAL',
      filterReplaced: false,
      createdAt: new Date('2025-12-25'),
    },
    {
      ticketNumber: 'AS-20251227-009',
      serviceDate: new Date('2025-12-27'),
      companyName: '클린에어 코리아',
      customerId: customer.id,
      customerName: '오준혁',
      customerPhone: '010-6767-8989',
      customerAddress: '서울시 영등포구 여의도동 606',
      productName: '쉴드에어 프로 맥스',
      modelNumber: 'SH-AP200',
      issueType: 'OTHER',
      issueTitle: '리모컨 작동 불량',
      issueDescription: '리모컨 버튼이 반응하지 않습니다.',
      status: 'RECEIVED',
      priority: 'LOW',
      filterReplaced: false,
      createdAt: new Date('2025-12-27'),
    },
    {
      ticketNumber: 'AS-20251228-010',
      serviceDate: new Date('2025-12-28'),
      companyName: '에어솔루션',
      customerId: customer.id,
      customerName: '신예은',
      customerPhone: '010-1010-2020',
      customerAddress: '서울시 중구 명동 707',
      productName: '쉴드에어 프로',
      modelNumber: 'SH-AP100',
      issueType: 'SENSOR',
      issueTitle: '자동 모드 오작동',
      issueDescription: '자동 모드에서 갑자기 최대 풍속으로 전환됩니다.',
      status: 'IN_PROGRESS',
      priority: 'HIGH',
      diagnosisResult: '공기질 센서 보정 필요',
      filterReplaced: false,
      createdAt: new Date('2025-12-28'),
    },
  ];

  // 데이터 삽입
  for (const data of asData) {
    await prisma.afterService.create({ data });
    console.log(`AS 데이터 생성: ${data.ticketNumber}`);
  }

  console.log(`\n총 ${asData.length}개의 AS 데이터가 생성되었습니다.`);
}

seedAfterService()
  .catch((e) => {
    console.error('시딩 오류:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
